### ISSUE TITLE
issue-01

### ISSUE THREAD

**Issue by pratyush06853** [suerfu/TesseractSim#1]
background flux generator develop.

**Comment by suerfu** [comment]
Background flux generator is ready to be used. It is contained in the latest commit to the master branch by using rock_X.mac (with geometry type 1).

**Comment by xinranli1993** [comment]
We just had a discussion and there is one question for you. How are we going the generate the decays for the physics simulation?
Say, if now we generate the template gamma spectrum for the U238 chain, does it represent the same spectrum of the rock? The template spectrum has one decay per isotope down the chain. Is it the same for the real activities in rocks?

**Comment by xinranli1993** [comment]
> Background flux generator is ready to be used. It is contained in the latest commit to the master branch by using rock_X.mac (with geometry type 1).

We will include the processing code from Pratyush as well.

**Comment by suerfu** [comment]
> We just had a discussion and there is one question for you. How are we going to generate the decays for the physics simulation? Say, if now we generate the template gamma spectrum for the U238 chain, does it represent the same spectrum of the rock? The template spectrum has one decay per isotope down the chain. Is it the same for the real activities in rocks?

What do you mean by physics simulation and the spectrum of the rock? Are you referring to if the U and Th chain will be under secular equilibrium?

**Comment by suerfu** [comment]
If your concern is about the secular equilibrium of the chain, then a single decay takes care of it. The out of equilibrium issue persists mainly for substances that have undergone chemical separation. For naturally existing objects with duration much longer than a few thousand years, the decay chain is almost certainly in equilibrium.

**Comment by xinranli1993** [comment]
> If your concern is about the secular equilibrium of the chain, then a single decay takes care of it. The out of equilibrium issue persists mainly for substances that have undergone chemical separation. For naturally existing objects with duration much longer than a few thousand years, the decay chain is almost certainly in equilibrium.

Ok, so you mean when in equilibrium, the activity of each isotope down the chain should be the same as simulating the chain from the top isotope.
