### ISSUE TITLE
load different set of geometry config file depending on the type

### ISSUE THREAD

**Issue by suerfu** [suerfu/TesseractSim#2]
Currently, the Tesseract geometry configuration gets loaded regardless of the type of geometry. The loading should be done within the if-statement only when the geometry is the correct type.
Also, the loading of configuration file should depend on the type of geometry, i.e., one should be able to load a different set of config files depending on the type.

**Comment by xinranli1993** [comment]
Resolved by adding if cases to the loadDimension function and moving it to GeometryConstructionMessenger, executed with user command `\geometry\construct`
